USE Galvez_DB

1
SELECT E.LASTNAME, E.FIRSTNAME, D.DEPTNAME
FROM EMPLOYEE E INNER JOIN DEPARTMENT D 
	 ON E.WORKDEPT = D.DEPTNO
ORDER BY E.FIRSTNAME, E.LASTNAME, D.DEPTNAME;

2
SELECT E.LASTNAME, E.FIRSTNAME, E.JOB, D.DEPTNAME
FROM EMPLOYEE E INNER JOIN DEPARTMENT D 
	 ON E.WORKDEPT = D.DEPTNO
WHERE D.DEPTNO BETWEEN 'AD2' AND 'D22' AND E.JOB != 'MANAGER'
ORDER BY E.FIRSTNAME, E.LASTNAME, E.JOB, D.DEPTNAME;

3
SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNAME
FROM DEPARTMENT D INNER JOIN EMPLOYEE E 
	 ON D.MGRNO = E.EMPNO
ORDER BY D.DEPTNAME;

4
SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNAME
FROM DEPARTMENT D INNER JOIN EMPLOYEE E 
	 ON D.DEPTNO = E.WORKDEPT
WHERE E.JOB = 'MANAGER'
ORDER BY D.DEPTNAME;

5
SELECT DISTINCT P.PROJNO, P.PROJNAME, EA.ACTNO
FROM PROJECT P INNER JOIN EMP_ACT EA 
	 ON P.PROJNO = EA.PROJNO
WHERE P.PROJNO LIKE 'AD%' OR P.PROJNO LIKE '%II'
ORDER BY P.PROJNO, EA.ACTNO;

6
SELECT DISTINCT P.PROJNO, P.PROJNAME, EA.EMPNO, E.LASTNAME, EA.ACTNO
FROM PROJECT P INNER JOIN EMP_ACT EA 
	 ON P.PROJNO = EA.PROJNO
			   INNER JOIN EMPLOYEE E ON EA.EMPNO = E.EMPNO
WHERE P.PROJNO IN ('AD3113', 'IF2000', 'MA2112', 'OP2012')
ORDER BY P.PROJNO, EA.ACTNO;

7
SELECT E.EMPNO, P.PROJNO, P.PROJNAME, EA.ACTNO, P.PRSTDATE
FROM EMP_ACT EA	INNER JOIN EMPLOYEE E 
	 ON EA.EMPNO = E.EMPNO
				INNER JOIN PROJECT P 
	 ON EA.PROJNO = P.PROJNO
WHERE EA.EMSTDATE BETWEEN '2011-10-01' AND '2011-10-31'
ORDER BY P.PROJNO, E.EMPNO, EA.ACTNO;

8
SELECT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EA.ACTNO
FROM EMPLOYEE E INNER JOIN EMP_ACT EA 
	 ON E.EMPNO = EA.EMPNO
				INNER JOIN PROJECT P 
	 ON EA.PROJNO = P.PROJNO
WHERE E.WORKDEPT = 'A00'
ORDER BY E.EMPNO, EA.ACTNO;

9
SELECT DISTINCT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EA.ACTNO
FROM EMPLOYEE E INNER JOIN EMP_ACT EA 
	 ON E.EMPNO = EA.EMPNO
				INNER JOIN PROJECT P 
	 ON EA.PROJNO = P.PROJNO
WHERE E.WORKDEPT BETWEEN 'A00' AND 'C01'
ORDER BY E.WORKDEPT, E.LASTNAME, EA.ACTNO;

10
SELECT EA.ACTNO, D.MGRNO, EA.EMSTDATE, P.PROJNO, E.LASTNAME
FROM EMP_ACT EA INNER JOIN PROJECT P 
	 ON EA.PROJNO = P.PROJNO
				INNER JOIN DEPARTMENT D 
	 ON P.DEPTNO = D.DEPTNO
				INNER JOIN EMPLOYEE E 
	 ON EA.EMPNO = E.EMPNO
WHERE EA.EMSTDATE >= '2011-10-15'
ORDER BY EA.ACTNO, EA.EMSTDATE;

11
SELECT E.WORKDEPT, M.LASTNAME, E.LASTNAME, E.HIREDATE, M.HIREDATE
FROM EMPLOYEE E INNER JOIN EMPLOYEE M 
	 ON E.WORKDEPT = M.WORKDEPT AND M.JOB = 'MANAGER'
WHERE E.HIREDATE < M.HIREDATE
	 AND E.WORKDEPT IN ('A00', 'C01', 'D01', 'E01')
ORDER BY E.LASTNAME;

12
SELECT F.FID, F.FNAME, FL.SBJCODE, FL.SBJTITLE, FL.UNITS, FL.SBJCODE 
FROM FACULTY F RIGHT OUTER JOIN FACULTY_LOAD FL 
	ON F.FID = FL.FLOAD 
ORDER BY FL.SBJCODE;

13
SELECT F.FID, F.FNAME, FL.SBJCODE, FL.SBJTITLE, FL.UNITS, FL.SBJCODE
FROM FACULTY F RIGHT OUTER JOIN FACULTY_LOAD FL 
	ON F.FID = FL.FLOAD
ORDER BY FL.SBJCODE;

14
SELECT F.FID, F.FNAME, F.RANK, C.COLCODE, C.COLNAME
FROM FACULTY F FULL OUTER JOIN COLLEGE C ON C.COLCODE = F.COLCODE
ORDER BY C.COLCODE;

15
SELECT F.FID, F.FNAME, F.GENDER, F.RANK, FL.SBJCODE, FL.SBJTITLE, C.COLCODE, C.COLNAME
FROM FACULTY F  FULL OUTER JOIN FACULTY_LOAD FL ON FL.FLOAD = F.FID
				FULL OUTER JOIN COLLEGE C ON C.COLCODE = F.COLCODE
ORDER BY FL.SBJCODE;